New input data script and um-setup improvements

diff --git a/usr/local/bin/um-setup b/usr/local/bin/um-setup
--- a/usr/local/bin/um-setup
+++ b/usr/local/bin/um-setup
@@ -1,42 +1,51 @@
 #!/bin/bash
 
 # Set up additional files for the UM:
-# 1) Check out, build and install GCOM
-# 2) Create keyword.cfg file
+# 1) Check out/copy, build and install GCOM
+# 2) Create keyword.cfg file for offline working
 
-if [ "$#" -gt 2 ]; then
-  echo "Usage: $(basename $0) [revision] [source]" 
+if [ "$#" -gt 1 ]; then
+  echo "Usage: $(basename $0) [GCOM source tree]"
   exit 1
 fi
 
-vn=HEAD
-src=fcm:gcom.x/trunk
+src=fcm:gcom.x/trunk@head
 if [[ -n "$1" ]]; then
-  vn=$1
+  src=$1
 fi
-echo "Installing GCOM from revision $vn"
-
-if [[ -n "$2" ]]; then
-  src=$2
-fi
-echo "Installing GCOM from source $src"
-
-# Check the combined pair is valid
-fcm info $src@$vn > /dev/null 2>&1 || exit "$src@$vn is not a valid URL"
 
 tmpdir=$(mktemp -d)
-cd $tmpdir
 
-echo "Checking out GCOM from $src@$vn"
-fcm co -q $src@$vn
-cd trunk
+if [[ $src =~ ^fcm:|^svn:|file: ]]; then
+  # A URL of some kind
+  # Check the location is valid and get the Last Changed Rev
+  rev=$(fcm info $src | awk '/Last Changed Rev/ {print $NF}')
+  if [[ -z $rev ]]; then
+    echo "Failed to find a source tree at $src"
+    exit 1
+  fi
+  vn="r$rev"
+  fcm co -q $src $tmpdir/gcom_wc
+else
+  # Assume working copy
+  if [[ ! -d $src ]]; then
+    echo "$src is not a recognised repository location or a valid directory"
+    exit 1
+  fi
+  vn=wc
+  cp -r $src $tmpdir/gcom_wc
+fi
+
+echo "Installing GCOM from $src"
+
+cd $tmpdir/gcom_wc
 echo "Running rose-stem to build GCOM"
 rose stem --group=all --name=gcom_install --new -- --debug
-echo "GCOM suite output at http://localhost/rose-bush/jobs/vagrant/gcom_install"
+echo "GCOM suite output at http://localhost/rose-bush/jobs/$USER/gcom_install"
 
 # copy dirs to right place (remember may have to overwrite...)
-gdir="/home/vagrant/umdir/gcom"
-cdir="/home/vagrant/cylc-run/gcom_install/work"
+gdir="$HOME/umdir/gcom"
+cdir="$HOME/cylc-run/gcom_install/work"
 
 cd $cdir
 prefix="gcom_rosestem"
@@ -46,10 +55,10 @@ serial32dir="vm32B_gfortran_serial/build"
 if [ -d "$prefix$mpichdir" ] || [ -d "$prefix$serialdir" ] || [ -d "$prefix$serial32dir"]; then
   echo "Found one or more GCOM build directories to install"
 else
-  exit 1 "Cannot find a GCOM build directory in $cdir"
+  exit 1 "Cannot find a GCOM build in $cdir"
 fi
 
-rm -rf $gdir/$vn
+rm -rf $gdir/$vn  # Remove any existing installation
 mkdir -p $gdir/$vn/$mpichdir
 mkdir -p $gdir/$vn/$serialdir
 mkdir -p $gdir/$vn/$serial32dir
@@ -57,27 +66,31 @@ cp -r $prefix$mpichdir/* $gdir/$vn/$mpichdir || echo "Failed to install parallel
 cp -r $prefix$serialdir/* $gdir/$vn/$serialdir || echo "Failed to install serial GCOM library"
 cp -r $prefix$serial32dir/* $gdir/$vn/$serial32dir || echo "Failed to install 32-bit serial GCOM library"
 
-# set up symlink 'default'; multiple gcom versions are permitted.
+# set up symlink 'default' in case there are multiple other installs
 cd $gdir
 rm -f default
 ln -s $vn default
 
-# Clean up; cylc-run directory is kept in case of problems.
+# Clean up
 rm -rf $tmpdir
 
-echo "GCOM library has been installed to /home/vagrant/umdir/gcom/default"
+echo "GCOM library has been installed to $HOME/umdir/gcom/default"
 
 echo "Setting up additional FCM keywords"
-mkdir -p ~/.metomi/fcm
-cat > ~/.metomi/fcm/keyword.cfg <<EOF
-location{primary}[um.xm] = https://code.metoffice.gov.uk/svn/um/main
+mkdir -p $HOME/.metomi/fcm
+echo "location{primary}[um.xm] = https://code.metoffice.gov.uk/svn/um/main
 location{primary}[jules.xm] = https://code.metoffice.gov.uk/svn/jules/main
 location{primary}[socrates.xm] = https://code.metoffice.gov.uk/svn/socrates/main
-location{primary}[um_aux.xm] = https://code.metoffice.gov.uk/svn/um/AUX
+location{primary}[um_aux.xm] = https://code.metoffice.gov.uk/svn/um/aux
 location{primary}[um_doc.xm] = https://code.metoffice.gov.uk/svn/um/doc
-EOF
+location{primary}[mule.xm] = https://code.metoffice.gov.uk/svn/um/mule
 
+location{prinary}[um.offline] = file://$HOME/source/um/offline
+location{prinary}[jules.offline] = file://$HOME/source/jules/offline
+location{prinary}[socrates.offline] = file://$HOME/source/socrates/offline
+location{prinary}[um_aux.offline] = file://$HOME/source/um_aux/offline
+location{prinary}[mule.offline] = file://$HOME/source/mule/offline" > $HOME/.metomi/fcm/keyword.cfg
+
+echo "Local FCM keywords created."
 echo
 echo "Finished."
-echo "To work offline, check out a working copy of the UM and run:"
-echo "rose stem --group=install_source [--source=<source1> ...]"
