modify install script to use um

diff --git a/usr/local/bin/um-setup b/usr/local/bin/um-setup
--- a/usr/local/bin/um-setup
+++ b/usr/local/bin/um-setup
@@ -76,7 +76,26 @@ function get_source_tree {
   src=$1
   tmpdir=$2
 
-  if [[ $src =~ ^fcm:|^svn:|^file:|^http:|^https: ]]; then
+  if [[ $src = *.git ]]; then
+    # A git url
+
+    # Split the source into url and git ref
+    delimiter=".git@"
+    s=$src$delimiter
+    array=();
+    while [[ $s ]]; do
+      array+=( "${s%%"$delimiter"*}" );
+      s=${s#*"$delimiter"};
+    done;
+    src=${array[0]}
+    if [[ $src != *.git ]]; then
+      src=$src.git
+    fi
+    ref=${array[1]}
+
+    git clone -q $src $tmpdir/wc || { echo "Failed to clone $src"; exit 1; }
+    git -C {$tmpdir/wc} checkout $ref || { echo "Failed to checkout $ref in $tmpdir/wc"; exit 1; }
+  elif [[ $src =~ ^fcm:|^svn:|^file:|^http:|^https: ]]; then
     # A URL of some kind
     # Check the location is valid and get the Last Changed Rev
     rev=$(fcm info $src | awk '/Last Changed Rev/ {print $NF}')
@@ -123,40 +142,13 @@ process_args $@
 
 cylc_version=${cylc_version:-'8'}
 gcom_src=${gcom_src:-'fcm:gcom.x/trunk@head'}
-shumlib_src=${shumlib_src:-'fcm:shumlib.x/trunk@head'}
+shumlib_src=${shumlib_src:-'git@github.com:MetOffice/shumlib.git'}
 
 echo "Preparing the VM for running the Unified Model"
 echo
 
 ##### .metomi setup #####
 
-echo "Setting up FCM keywords..."
-mkdir -p $HOME/.metomi/fcm
-touch $HOME/.metomi/fcm/keyword.cfg
-
-create_keyword 'um.xm' "https://code.metoffice.gov.uk/svn/um/main"
-create_keyword 'jules.xm' "https://code.metoffice.gov.uk/svn/jules/main"
-create_keyword 'socrates.xm' "https://code.metoffice.gov.uk/svn/socrates/main"
-create_keyword 'casim.xm' "https://code.metoffice.gov.uk/svn/monc/casim"
-create_keyword 'ukca.xm' "https://code.metoffice.gov.uk/svn/ukca/main"
-create_keyword 'um_aux.xm' "https://code.metoffice.gov.uk/svn/um/aux"
-create_keyword 'um_doc.xm' "https://code.metoffice.gov.uk/svn/um/doc"
-create_keyword 'um_meta.xm' "https://code.metoffice.gov.uk/svn/um/meta"
-create_keyword 'mule.xm' "https://code.metoffice.gov.uk/svn/um/mule"
-create_keyword 'moci.xm' "https://code.metoffice.gov.uk/svn/moci/main"
-create_keyword 'shumlib.xm' "https://code.metoffice.gov.uk/svn/utils/shumlib"
-create_keyword 'lfric_apps.xm' "https://code.metoffice.gov.uk/svn/lfric_apps/main"
-create_keyword 'um.offline' "file://$HOME/source/um/offline"
-create_keyword 'jules.offline' "file://$HOME/source/jules/offline"
-create_keyword 'socrates.offline' "file://$HOME/source/socrates/offline"
-create_keyword 'casim.offline' "file://$HOME/source/casim/offline"
-create_keyword 'ukca.offline' "file://$HOME/source/ukca/offline"
-create_keyword 'um_aux.offline' "file://$HOME/source/um_aux/offline"
-create_keyword 'mule.offline' "file://$HOME/source/mule/offline"
-create_keyword 'shumlib.offline' "file://$HOME/source/shumlib/offline"
-
-echo "Local FCM keywords created."
-echo
 echo 'Adding rose-ana settings to ~/.metomi/rose.conf for KGO auto-generation...'
 conf_file="$HOME/.metomi/rose.conf"
 
@@ -289,7 +281,7 @@ for shum_omp in true false; do
 
 
   # Remove any previous builds
-  make -f make/${vm_config}.mk clean > /dev/null 2>&1 
+  make -f make/${vm_config}.mk clean > /dev/null 2>&1
 
   # Build the library
   echo
